### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by TY-cc** [ShallMate/OKVS#1]
An error occurred when I used the command “make”, as follows

> In file included from /home/cc/OKVS/OKVS/Paxos.h:20,
                 from /home/cc/OKVS/OKVS/main.cpp:6:
/home/cc/OKVS/OKVS/PxUtil.h:13:10: fatal error: libdivide.h: No such file or directory
   13 | #include "libdivide.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/main.dir/build.make:76: CMakeFiles/main.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Which dependency library does “libdivide.h” belong to ?

**Comment by ShallMate** [comment]
Thank you for the issue. You can find libdivide.h on https://github.com/ridiculousfish/libdivide, and build it as follows. I will update the Readme about libdivide.h.
![QQ截图20221226141011](https://user-images.githubusercontent.com/25976948/209510292-d794be57-6d1e-4417-aebe-0f701b941f6f.png)

**Comment by TY-cc** [comment]
Thanks for your reply, I have successfully compiled.
